### ISSUE TITLE
Duvida - Arquivo de Importação de Anunciantes em Lote

### ISSUE THREAD

**Issue by GabrielRodriguesS** [grupozap/crm-lead-integration#10]
Enviando o arquivo CSV para integracaoleads@grupozap.com com os dados dos clientes eu estarei me inscrevendo para receber os leads apenas desses clientes?

Se sim, para adicionar novos clientes só preciso reenviar o CSV para passar a receber os leads gerados nos seus imoveis?

Resumindo como faço para receber apenas os leads de um conjunto de clientes?
E como adicionar e remover dinamicamente essa lista de clientes?

**Comment by rbarbioni** [comment]
O arquivo csv será utilizado somente para a primeira carga de clientes/integrações em comum com nossos portais. Para os demais clientes que o CRM adquirir, O CRM deverá enviar a url de integração orientar os clientes a entrarem em contato com nosso time de Soluções Integradas (Suporte ao Cliente) para que eles ativem a integração pontualmente.
Ainda não temos uma forma automatizada de fazer a gestão das integrações por CRM.

**Comment by GabrielRodriguesS** [comment]
Em média quanto tempo demora todo esse tramite?
Existe algum roadmap que eu possa acompanhar para saber se consigo criar um serviço para adicionar e excluir dinamicamente uma integração por CRM?
Obrigado desde já! :)

**Comment by rbarbioni** [comment]
Bom dia Gabriel, desculpe a demora, tivemos um problema interno e esta issue não foi notificada.
Normalmente demora de 1 a 5 dias para as integrações em lote serem ativadas, vai depender muito se os CPF/CNPJ vão bater com nossa base!
Ainda não temos nenhum fuxo sobre o andamento do processo, pois é feito manualmente! Será respondido no seu e-mail na thread original da solicitação.

**Comment by GabrielRodriguesS** [comment]
Sem problemas, agradeço a resposta e já entendi como se dá o funcionamento da integração, novamente muito obrigado!
