### ISSUE TITLE
DÚVIDA SOBRE MANUAL

### ISSUE THREAD

**Issue by brunoFallis** [grupozap/crm-lead-integration#12]
Boa tarde, 

Estou fazendo a integração de LEADS, porém durante o desenvolvimento encontrei outro manual de leads na RDSTATION e nele existe um campo a mais :

**originListingTitle**: nome do imóvel do anúncio.

URL do manual: https://ajuda.rdstation.com.br/hc/pt-br/articles/360026269391-Como-integrar-com-VivaReal-Zap-Im%C3%B3veis-

Já neste manual aqui no GIT não encontrei este campo, qual seria o correto ?

Minha segunda dúvida é se tem como eu saber se o imóvel que veio é de VENDA ou se é de LOCAÇÃO durante a chamada com o LEAD ? Caso sim, como posso pegá-lo, não encontrei no manual.

**Comment by rbarbioni** [comment]
Olá Bruno.
Desculpe a demora, tivemos um problema interno e esta issue não foi notificada.
O campo `originListingTitle` foi adicionada somente para a integração com a RDStation, pois eles precisam desta info de forma particular.
Sobre `VENDA` ou `ALUGUEL` ainda não estamos enviando na integração, estamos fazenodo um planejamento para a inclusão, porém ainda não temos previsão!
Dúvidas estou a disposição
