### ISSUE TITLE
[Dúvida] - Integração com mais de um cliente

### ISSUE THREAD

**Issue by giovannicarmo** [grupozap/crm-lead-integration#13]
Olá!
Faço parte da equipe de um software de pré-venda que atende mais de uma empresa que faz uso dos portais do Grupo Zap.

Analizando os endpoits de vocês, gostaria de alinhar alguns pontos para saber se entendi corretamente e tirar algumas dúvidas:

- O ID-DO-ANUNCIANTE será relacionado com o ID do usuário do cliente presente em meu software, correto? Como vocês reconheceriam esta relação? E no caso de não informar o ID-DO-ANUNCIANTE pela url, qual seria a resposta obtita pela requisição e como faria para vincular com o ciente em meu software?

- Após prepararmos nosso sistema para receber os dados de vocês lhes fornecermos a url, os leads das plataformas do Grupo Zap cairão em nosso sistema através de um Webhook, correto.

- Em meu entendimento, o campo clientListingId seria o identificador do negócio. Através deste identificador, consigo por algum endpoint trazer mais dados sobre o mesmo?
Exemplo.: Link da página e tipo do anúncio (locação ou venda) ?

Desde já agradeço.
Att,

**Comment by rbarbioni** [comment]
> **O ID-DO-ANUNCIANTE será relacionado com o ID do usuário do cliente presente em meu software, correto? Como vocês reconheceriam esta relação?** *
No final da implementação o responsável pela implementação parceiro deverá enviar a relação no e-mail `integracaoleads@grupozap.com`. Tem também a opção de gerar um CSV como descrito na documentação:
https://github.com/grupozap/crm-lead-integration#arquivo-de-importa%C3%A7%C3%A3o-de-anunciantes-em-lote

> **E no caso de não informar o ID-DO-ANUNCIANTE pela url, qual seria a resposta obtita pela requisição e como faria para vincular com o ciente em meu software?**
Neste caso o software integrador deverá identificar o cliente por `clientListingId` que é enviada no payload da integração. 

> **Após prepararmos nosso sistema para receber os dados de vocês lhes fornecermos a url, os leads das plataformas do Grupo Zap cairão em nosso sistema através de um Webhook, correto?**
Sim, nosso sistema fará um POST na URL (webhook) da integração no momento que o lead for gerado nos portais!

> **Em meu entendimento, o campo clientListingId seria o identificador do negócio. Através deste identificador, consigo por algum endpoint trazer mais dados sobre o mesmo?**
Não temos APIs de consuta de lead!
>   **Exemplo.: Link da página e tipo do anúncio (locação ou venda) ?**
Não temos APIs de consuta de lead!

Dúvida estou a disposição
