### ISSUE TITLE
Solicitação de SECRET_KEY e testes

### ISSUE THREAD

**Issue by GabrielDGennaro** [grupozap/crm-lead-integration#16]
Realizei a solicitação da secret_key por e-mail, mas não obtive nenhum retorno, gostaria de saber se está tudo certo com o endpoint enviado.

**Comment by rbarbioni** [comment]
Olá Gabriel.
Não encontrei a solicitação, poderia enviar novamente no e-mail [integracaoleads@grupozap.com](integracaoleads@grupozap.com) por favor?
Fico no aguardo

**Comment by juizmill** [comment]
Olá o SECRET_KEY é fornecido por vocês ou eu envio da minha API e vocês configura na integração?

**Comment by GabrielDGennaro** [comment]
Bom dia!

Já realizei a integração com vocês, outro colaborador já desenvolveu a parte do zap e está tudo funcionando.

 

Atenciosamente,

 





Gabriel De Gennaro


Desenvolvimento Web | Nonio


 <tel:(11)%203842-9267> (11) 3842-9267


gabriel.gennaro@nonio.com.br <mailto:gabriel.gennaro@nonio.com.br> 


 <http://www.nonio.com.br/> www.nonio.com.br

**Comment by blackcat1383** [comment]
Bom dia!

**Comment by blackcat1383** [comment]
Bom dia @GabrielDGennaro e @juizmill , o último e-mail que temos parecia que a integração havia sido finalizada com sucesso (abaixo). Ainda existe alguma pendencia?

> Renan, boa tarde!

> Verifiquei junto a imobiliária que o clientListingId contemplam dois códigos que tenho acesso aqui, então problema resolvido.

> Agradeço a atenção!
> Atenciosamente,

**Comment by GabrielDGennaro** [comment]
Ana Carolina, bom dia!

Não existe nenhuma pendência, já concluímos a integração.

Atenciosamente,

 





Gabriel De Gennaro


Desenvolvimento Web | Nonio


 <tel:(11)%203842-9267> (11) 3842-9267


gabriel.gennaro@nonio.com.br <mailto:gabriel.gennaro@nonio.com.br> 


 <http://www.nonio.com.br/> www.nonio.com.br
