### ISSUE TITLE
Iniciando testes de Integração 

### ISSUE THREAD

**Issue by azeredogab** [grupozap/crm-lead-integration#17]
Olá, boa tarde! 

Estamos iniciando os testes de integração de lead com o ZAP. Acabamos de enviar um e-mail para integracaoleads@grupozap.com, como solicitado nas instruções. 

Gostaria de saber melhor quanto tempo, em média, demora para habilitarmos a integração ?

**Comment by blackcat1383** [comment]
Bom dia @azeredogab ! Geralmente em três dias. Qual o CRM que você representa? Ainda está com alguma pendência?
