### ISSUE TITLE
Envio dos Leads - mais informações

### ISSUE THREAD

**Issue by ederaldooc** [grupozap/crm-lead-integration#18]
Bom dia !

Gostaria de solicitar que no "Contrato JSON", enviado para os sistema que fazem a integração com o grupozap também seja enviado o departamento, por exemplo, venda ou locação.

Obrigado.

**Comment by blackcat1383** [comment]
Bom dia, @ederaldooc ! No momento não é possível enviar esta informação. Mas isto já está em nosso backlog! :grin:
