### ISSUE TITLE
Posso usar ferramenta de integração?

### ISSUE THREAD

**Issue by davidcantidio** [grupozap/crm-lead-integration#22]
Olá, 

Utilizo www.integromat.com para integração de Leads com CRM.  Ele gera uma url de webhook tipo essa: https://hook.integromat.com/29dffqtkelv4tuwfrvkurl0vqfcgro6t  para receber as informações. 

Seria possível utilizar um endereço como esse para receber os dados de vocês?

**Comment by luccakazan** [comment]
Oi @davidcantidio , tudo bem?
Hoje não integramos com a Integromat. Integramos apenas diretamente com os softwares CRM via webhook.
