### ISSUE TITLE
Integração de Leads - Id do anunciante via Query Params

### ISSUE THREAD

**Issue by leomibking** [grupozap/crm-lead-integration#26]
Na documentação do envio de leads, as 2 formas possíveis de enviar o id do anunciante é via path (`https://yourdomain.com.br/grupozap/lead/ID-DO-ANUNCIANTE`) ou via url (`https://ID-DO-ANUNCIANTE.yourdomain.com.br/grupozap/lead`).

Gostaria de saber, se é possivel enviar ele via Query String, no formato: `https://yourdomain.com.br/grupozap/lead?idAnunciante=ID-DO-ANUNCIANTE`

Outra duvida, a secret key que vcs enviam na autenticação (`https://github.com/grupozap/crm-lead-integration/wiki/Como-Validar-Seguran%C3%A7a-SECRET_KEY`) é 1 por cliente/integração ou 1 por integradora (nós) independente dos clientes?

**Comment by marcieltorres** [comment]
Eaí @leomibking beleza? Suportamos sim via querystring, após homologação (seguindo nosso manual https://developers.grupozap.com/leads/integration/#homologacao) podemos configurar para enviar o id do anunciante nesse formato.

Com relação ao token, ele é único por software integrador, então vocês vão receber um para o ambiente de produção (após homologação) e o token que está na documentação serve para nosso ambiente de homologação apenas.

:)

**Comment by leomibking** [comment]
Ah sim, muito obrigado!
