### ISSUE TITLE
Dúvida sobre o endpoints

### ISSUE THREAD

**Issue by fernandomacoli** [grupozap/crm-lead-integration#28]
É feita essa informação "Abaixo exemplos de endpoints que **poderão ser utilizados**:", neste caso não poderemos utilizar outro, tipo: https://meudominio.net/servicos/portal/grupozap/lead/12345

**Comment by marcieltorres** [comment]
@fernandomacoli é o possível usar esse outro formato sim:

`https://meudominio.net/servicos/portal/grupozap/lead/<ID_DO_ANUNCIANTE>`

**Comment by fernandomacoli** [comment]
Obrigado!!!
