### ISSUE TITLE
Ola!

### ISSUE THREAD

**Issue by N3R00** [grupozap/crm-lead-integration#3]
Peço, por favor que sejam mais claros na documentação desta API, há muita informação vaga, seria bom se tivesse um exemplo ou algo assim...

**Comment by andrelrs** [comment]
Oi @N3R00 não entendi o questionamento. Um exemplo do que? Consegue ser mais especifico no time de informação que está faltando. Obrigado.

**Comment by N3R00** [comment]
Vocês dizem que precisam de um ENDPOINT e que vão passar os parametros via POST, mas não dizem quais são esses parametros...

**Comment by N3R00** [comment]
Dizem que vão enviar um JSON, mas a partir do que? eu preciso fazer oq exatamente? receber esse JSON que sera passado por um parametro por POST? ou sera enviado um arquivo com um JSON dentro?

Tem mt informação vaga...

**Comment by andrelrs** [comment]
@N3R00 segue a explicação. https://github.com/grupozap/crm-lead-integration#envio-dos-leads

Como dito na própria documentação. 

> Os leads serão enviados via protocolo HTTP no verbo POST passando um JSON com as informações do lead no endpoint (URL) especificado e homologado por nosso time.

Na mesma diz o contrato que será enviado no corpo do HTTP.

> Contrato JSON:

`{
  "leadOrigin": "VivaReal",
  "timestamp": "2017-10-23T15:50:30.619Z",
  "originLeadId": "59ee0fc6e4b043e1b2a6d863",
  "originListingId": "87027856",
  "clientListingId": "a40171",
  "name": "Nome Consumidor",
  "email": "nome.consumidor@email.com",
  "ddd": "11",
  "phone": "999999999",
  "phoneNumber": "11999999999",
  "message": Olá, tenho interesse neste imóvel. Aguardo o contato. Obrigado.",
}`

**Comment by N3R00** [comment]
"O controle do status de recebimento dos leads será feito exclusivamente através dos códigos de status do protocolo HTTP, qualquer informação enviada no corpo da resposta será totalmente ignorada."

Também não entendi essa parte, vcs enviaram a requisição, eu receberei os dados via POST, e caso esteja tudo certo eu retorno 200, senão retornarei qlqr outra 3xx, 4xx e talz, como eu retorno pelo " códigos de status do protocolo HTTP" ????

**Comment by N3R00** [comment]
> @N3R00 segue a explicação. https://github.com/grupozap/crm-lead-integration#envio-dos-leads
> 
> Como dito na própria documentação.
> 
> > Os leads serão enviados via protocolo HTTP no verbo POST passando um JSON com as informações do lead no endpoint (URL) especificado e homologado por nosso time.
> 
> Na mesma diz o contrato que será enviado no corpo do HTTP.
> 
> > Contrato JSON:
> 
> `{ "leadOrigin": "VivaReal", "timestamp": "2017-10-23T15:50:30.619Z", "originLeadId": "59ee0fc6e4b043e1b2a6d863", "originListingId": "87027856", "clientListingId": "a40171", "name": "Nome Consumidor", "email": "nome.consumidor@email.com", "ddd": "11", "phone": "999999999", "phoneNumber": "11999999999", "message": Olá, tenho interesse neste imóvel. Aguardo o contato. Obrigado.", }`

Agr entendi o esquema, a explicação de vcs q é bem vaga, vcs enviaram atraves do verbo POST, porém os dados enviados serão em JSON

ou seja, qnd eu receber no meu codigo, receberei como post.

**Comment by andrelrs** [comment]
@N3R00 https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status

Padrão do protocolo HTTP.
