### ISSUE TITLE
Ajuda para integração com PHP

### ISSUE THREAD

**Issue by xistooooo** [grupozap/crm-lead-integration#32]
Alguém poderia me mandar um exemplo do Script que recebe a requisição que eles enviam por post e salva o lead e um txt?
estou no email contato@gestaoimoveis.com

**Comment by xistooooo** [comment]
isso foi o mais perto que eu cheguei e sei que não estou nem perto
<?php
	$username="";
	$password="";
	if(isset($_SERVER['PHP_AUTH_USER'])){ // Método para mod_php (Apache){
		list($username,$password )=explode(':',base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'],6));
	}

	if($password== "x" AND $username== "x"){
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 200 OK');
		echo "recebe json";
		
	}else{
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 401 Unauthorized');
		die('Acesso negado.');
	}
?>

**Comment by xistooooo** [comment]
`<?php
	$username="";
	$password="";
	if(isset($_SERVER['PHP_AUTH_USER'])){ // Método para mod_php (Apache){
		list($username,$password )=explode(':',base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'],6));
	}

	if($password== "x" AND $username== "x"){
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 200 OK');
		echo "recebe json";
		
	}else{
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 401 Unauthorized');
		die('Acesso negado.');
	}
?>`

**Comment by xistooooo** [comment]
<?php
	$username="";
	$password="";
	if(isset($_SERVER['PHP_AUTH_USER'])){ // Método para mod_php (Apache){
		list($username,$password )=explode(':',base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'],6));
	}

	if($password== "x" AND $username== "x"){
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 200 OK');
		echo "recebe json";
		
	}else{
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 401 Unauthorized');
		die('Acesso negado.');
	}
?>
```

**Comment by marcieltorres** [comment]
https://github.com/grupozap/crm-lead-integration/wiki/Como-Validar-Seguran%C3%A7a-SECRET_KEY

**Comment by xistooooo** [comment]
só que ai não fala nada em php, se for pegar a primeira linha que ta escrito ` const authorization = req.headers.Authorization; `
e colar no php já da erro. Eu preciso em PHP

**Comment by xistooooo** [comment]
mais perto que eu cheguei no php foi isso
`$username="";
	$password="";
	if(isset($_SERVER['PHP_AUTH_USER'])){
		list($username,$password )=explode(':',base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'],6));
	}

	if($password== "x" AND $username== "x"){ //usei x pra teste
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 200 OK');
		echo "recebe json";
		
	}else{
		header('WWW-Authenticate: Basic realm="Sistema de Testes"');
		header('HTTP/1.0 401 Unauthorized');
		die('Acesso negado.');
	}`

**Comment by marcieltorres** [comment]
Não temos modelos em PHP

**Comment by marcieltorres** [comment]
@xistooooo vc precisa fazer algo assim: https://www.php.net/manual/pt_BR/function.get-headers.php e validar o header que a gente envia.

Essa validação do header é apenas para vocês saberem que somos nós que estamos enviando o lead.

**Comment by xistooooo** [comment]
` cheguei neste código, vou entrar em contato com eles para solicitar o secret e ver se chega alguma coisa
<?php
	if(!isset($_SERVER["PHP_AUTH_USER"])){
		header("WWW-Authenticate: Basic");
		
		header("HTTP/1.0 401 Unauthorized");
		
		echo "Operação cancelada! Você não logou!!"; exit;
		
	}else{
		
		list($user, $pass) = explode(":",base64_decode(substr($_SERVER["HTTP_AUTHORIZATION"], 6)));
		
		$secret="";//seu secret aqui
		
		if($pass==$secret){
			
			$conteudo=file_get_contents('php://input');
			
			file_put_contents('lead_zap.txt',$conteudo);
			
		}else{
			
			header("HTTP/1.0 401 Unauthorized");
			
		}
		
	}
?>
`

**Comment by xistooooo** [comment]
cheguei neste código, vou entrar em contato com eles para solicitar o secret e ver se chega alguma coisa

`
<?php
	if(!isset($_SERVER["PHP_AUTH_USER"])){
		header("WWW-Authenticate: Basic");
		
		header("HTTP/1.0 401 Unauthorized");
		
		echo "Operação cancelada! Você não logou!!"; exit;
		
	}else{
		
		list($user, $pass) = explode(":",base64_decode(substr($_SERVER["HTTP_AUTHORIZATION"], 6)));
		
		$secret="";//seu secret aqui
		
		if($pass==$secret){
			
			$conteudo=file_get_contents('php://input');
			
			file_put_contents('lead_zap.txt',$conteudo);
			
		}else{
			
			header("HTTP/1.0 401 Unauthorized");
			
		}
		
	}
?>

`

**Comment by xistooooo** [comment]
cheguei neste código, vou entrar em contato com eles para solicitar o secret e ver se chega alguma coisa

<?php
	if(!isset($_SERVER["PHP_AUTH_USER"])){
		header("WWW-Authenticate: Basic");
		
		header("HTTP/1.0 401 Unauthorized");
		
		echo "Operação cancelada! Você não logou!!"; exit;
		
	}else{
		
		list($user, $pass) = explode(":",base64_decode(substr($_SERVER["HTTP_AUTHORIZATION"], 6)));
		
		$secret="";//seu secret aqui
		
		if($pass==$secret){
			
			$conteudo=file_get_contents('php://input');
			
			file_put_contents('lead_zap.txt',$conteudo);
			
		}else{
			
			header("HTTP/1.0 401 Unauthorized");
			
		}
		
	}
?>

**Comment by xistooooo** [comment]
cheguei neste código, vou entrar em contato com eles para solicitar o secret e ver se chega alguma coisa

`
if(!isset($_SERVER["PHP_AUTH_USER"])){
		header("WWW-Authenticate: Basic");
		
		header("HTTP/1.0 401 Unauthorized");
		
		echo "Operação cancelada! Você não logou!!"; exit;
		
	}else{
		
		list($user, $pass) = explode(":",base64_decode(substr($_SERVER["HTTP_AUTHORIZATION"], 6)));
		
		$secret="";//seu secret aqui
		
		if($pass==$secret){
			
			$conteudo=file_get_contents('php://input');
			
			file_put_contents('lead_zap.txt',$conteudo);
			
		}else{
			
			header("HTTP/1.0 401 Unauthorized");
			
		}
		
	}
 `
