### ISSUE TITLE
Esclarecimento

### ISSUE THREAD

**Issue by ticianorego** [grupozap/crm-lead-integration#4]
Gostaria de entender sobre a integração entre CRM e o ZAP e Viva Real.

A integração será dos leads gerados dentro dos sites do ZAP e/ou Viva Real para o CRM da imobiliária ?

Caso positivo onde teremos que incluir o código ? E poderemos usar o Sua House como CRM ?

**Comment by rbarbioni** [comment]
**A integração será dos leads gerados dentro dos sites do ZAP e/ou Viva Real para o CRM da imobiliária ?**
Sim, o lead é enviado praticamente em tempo real para o CRM previamente homologado!

**Caso positivo onde teremos que incluir o código ? E poderemos usar o Sua House como CRM ?**
Sim. SuaHouse CRM já tem a integração de leads com os portais ZapImóveis e VivaReal funcionando 100%.
