### ISSUE TITLE
Dúvida sobre a integração

### ISSUE THREAD

**Issue by diegolpedrosa** [grupozap/crm-lead-integration#5]
Boa tarde amigos,

Dei uma lida na documentação de vocês sobre a integração de Leads junto ao sistema de vocês, porém estou com dúvida neste trecho:

"Estamos disponibilizando neste repositório o manual de Integração de Leads do Grupo Zap. Este documento contém as informações básicas para os Softwares/CRM realizarem as integracões com nosso sistema afim de receber os leads gerados nos portais do GrupoZap (VivaReal e ZapImoveis). Basicamente nosso sistema de integração de leads precisa de uma URL (Endpoint) para enviar as informações do lead para os softwares homologados, esta requisição será realizada via protocolo HTTP no verbo POST no Endpoint especificado passando um JSON como corpo do request."

A integração é apenas dos Leads gerados a partir dos portais de vocês ? Mas como eu vou criar essas requisições nos portais de vocês ? No meu entendimento eu controlaria os Leads gerados a partir do site da MINHA imobiliária e enviaria para o sistema de vocês a fim de gerencia-los lá. Não seria assim ? Podem me explicar, obrigado !

**Comment by diegolpedrosa** [comment]
Aguardando resposta ainda.

**Comment by rbarbioni** [comment]
Ola @diegolpedrosa 
A conforme repondido pelo @N3R00 nossa integração funciona de forma reativa com os CRMs.
Quando um lead é gerado nos portais Zap e VivaReal, nosso sistema faz a requisição no endpoint (Api Rest) criado pelo CRM/Sistema da imobiliária que o mesmo receberá o lead no mesmo instante que foi gerado nos portais. Ou seja, quem deve realizar a implementação e criar o endpoint de recebimento de lead é o CRM/Sistema Imobiliário
