### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by N3R00** [grupozap/crm-lead-integration#6]
Fiz a integração com vocês, porém, quando feito um pedido em algum anuncio, eu mando mostrar tudo que chega para o meu arquivo que veio atraves do post, e ele me retorna somente o numero 1, nada mais alem disso...

Segue meu codigo:

$escreve = fwrite($fp, "Dados do post: ".print_r($_POST));
$escreve = fwrite($fp, "Recuperando dados passados por POST:");

//RECEBE VALORES POST
$leadOrigin 		= $_POST['leadOrigin'];
$timestamp 			= $_POST['timestamp'];
$originLeadId 		= $_POST['originLeadId'];
$originListingId 	= $_POST['originListingId'];
$clientListingId 	= $_POST['clientListingId'];
$name 				= $_POST['name'];
$email 				= $_POST['email'];
$ddd 				= $_POST['ddd'];
$phone 				= $_POST['phone'];
$phoneNumber 		= $_POST['phoneNumber'];
$message 			= $_POST['message'];

**Comment by alisson04** [comment]
Bom dia, conseguiu resolver? Não estou conseguindo pegar a Basic Authorization
