### ISSUE TITLE
Problemas no recebimento de Leads

### ISSUE THREAD

**Issue by julioRicardoMN** [grupozap/crm-lead-integration#7]
Boa tarde, 
Faço parte de uma empresa que realiza a integração com o grupoZap, não tivemos problemas com a criação do webhook e seu manual está muito bem detalhado em relação as funções. No entanto, notamos que alguns clientes nossos começaram a reclamar que não estavam recebendo os leads no sistema, reparamos que são casos mais isolados, pois recebemos centenas por dia via a integração. Após uma análise, descobrimos que em alguns casos vocês estão enviando como método GET quando o correto seria um método POST.
Tenho como exemplo um teste que realizamos na empresa 343626.
{
  "clientListingId": "CA000147",
  "email": "vp-junior@bol.com.br",
  "leadOrigin": "VivaReal",
  "message": "Teste de integração, favor desconsiderar.",
  "name": "Teste PJ",
  "originLeadId": "5ca649a6e4b0bfb52d2e1f61",
  "originListingId": "2436508634",
  "ddd": "",
  "phone": "",
  "phoneNumber": "",
  "timestamp": "2019-04-04T18:15:02.331Z"
}
Criamos uma rota para o método GET e graças a isso foi possível que a nossa api começa-se a responder um erro 500 ao invés de 404. Porém ainda não é possível ler o "body", acredito que por se tratar de um GET não seja possível receber essa informação, pois ela vem apenas um JSON vazio {}.
Estamos no aguardo para resolvermos esse problema, pois eu já enviei um e-mail e não obtive resposta.
Qualquer dúvida estou a disposição.

**Comment by rbarbioni** [comment]
Muito estranho isso, o sistema de leads faz somente POST nas urls de integração. Vou abir uma issue interna pra investigar este caso.
Parece estar acontecendo somente com a integração de vocês!

**Comment by rbarbioni** [comment]
Resolvido: 
Problema com redirect (location) http -> https devido a url erradas.
Corrigido!
