### ISSUE TITLE
Dúvida sobre o campo ID-DO-ANUNCIANTE

### ISSUE THREAD

**Issue by jacsonFJ** [grupozap/crm-lead-integration#8]
O campo ID-DO-ANUNCIANTE é o id do anunciante no grupo zap, ou o id do anunciante no CRM?

**Comment by rbarbioni** [comment]
Código/ID/username da imobiliária no CRM.
Pode ser usado caso o CRM escolha ter o identificador do seu cliente na URL de integração, assim facilitando a sua identificação e associação quando receber o lead.
