### ISSUE TITLE
Duvida sobre importação de anunciantes

### ISSUE THREAD

**Issue by brunochikuji** [grupozap/crm-lead-integration#9]
Bom dia.

Eu olhei na documentação de vocês que após a homologação ira ser necessário enviar um arquivo csv com todos os anunciantes que possuem integração com os portais ZAP ou VivaReal.

Porem eu queria saber como ira ser após isso com os novos clientes que forem ativando a integração? 
Eu vou precisar enviar o arquivo .csv só com o cliente que ativou a integração, ou com todos os clientes novamente?

**Comment by rbarbioni** [comment]
Fala Bruno, beleza!
O csv será somente utilizado para a primeira carga de clientes/integrações. Para os demais clientes em comum que que seu CRM adquirir, vocês deverão enviar para eles a url de integração e orientar para ele entrar em contato com nosso time de Atendimento ao Cliente que faremos a ativação da integração.

**Viva Real:** 3150-4646
**ZAP:** 4005-9111 ou 0800-940-9111

### Chat
**ZAP:** https://zapimoveis.zendesk.com/hc/pt-br#ajuda-para-quem-anuncia
**VivaReal:** https://zapvivareal.zendesk.com/hc/pt-br#ajuda-para-quem-anuncia

**Comment by brunochikuji** [comment]
Renan,
Bom dia.

Obrigado pelo retorno, iremos seguir esse procedimento então.
